name = "2fauth-cloudflare"
main = "src/worker.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "worker-2fauth-db"
database_id = "b388dc9b-021e-4184-a256-5599139acfa6"

[vars]
ALLOW_PLAINTEXT_EXPORT = "false"
